config/routes.rb
SimpleLib::Application.routes.draw do
  devise_for :users, :path_prefix => 'auth'

  resources :users, :only => :index
  resources :users, :only => :show do
    resources :books
  end

  resources :books, :only => [:index, :show]

  root :to => 'home#index'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user, counter_cache: true
  has_attached_file :bookfile

  # attributes
  attr_accessible :title, :description, :bookfile
  normalize_attributes :title, :description

  # validation
  validates :title, presence: true, uniqueness: { scope: :user_id }
  validates_attachment_presence :bookfile
  validates_attachment_content_type :bookfile, content_type: ['application/pdf'], message: 'not pdf file'

  # scopes
  def self.recently_added count = 5
    unscoped.order(:created_at).reverse_order.limit(count)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # attributes
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  normalize_attributes :name

  # validation
  validates :name, presence: true

  # scopes
  TOP_BY_COUNT_OF_BOOKS = 3 # used in view
  scope :by_count_of_books, where("books_count > '0'").order('books_count desc').order(:name).limit(TOP_BY_COUNT_OF_BOOKS)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!, except: [:index, :show]

  unless Rails.application.config.consider_all_requests_local
    rescue_from Exception,
                with: lambda { |exception| render_error 500, exception }

    rescue_from ActionController::RoutingError,
                ActionController::UnknownController,
                ::AbstractController::ActionNotFound,
                ActiveRecord::RecordNotFound,
                with: lambda { |exception| render_error 404, exception }
  end

  private

  def render_error(status, exception = nil)
    respond_to do |format|
      format.html { render template: "errors/error_#{status}", layout: 'layouts/error', status: status }
      format.all { render nothing: true, status: status }
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :find_author, only: [:index, :show]

  def index
    @books = @author ? @author.books : Book.order(:title)
  end

  def show
    @book = @author ? @author.books.find(params[:id]) : Book.find(params[:id])
  end

  def new
    @book = current_user.books.new
  end

  def edit
    @book = current_user.books.find(params[:id])
  end

  def create
    @book = current_user.books.new(params[:book])

    if @book.save
      redirect_to [current_user, @book], notice: 'Book was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @book = current_user.books.find(params[:id])

    if @book.update_attributes(params[:book])
      redirect_to [current_user, @book], notice: 'Book was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @book = current_user.books.find(params[:id])
    @book.destroy

    redirect_to user_books_url(current_user)
  end

  private

  def find_author
    @author = params[:user_id] ? User.find(params[:user_id]) : nil
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def error_404
    @not_found_path = params[:not_found]
    render_error(404)
  end

  def error_500
    render_error(500)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recently_added_books = Book.recently_added
    @user_by_count_of_books = User.by_count_of_books
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_download_book.html.erb
<%= link_to download_book.bookfile_file_name, download_book.bookfile.url, title: 'Download', target: '_blank' %>

app/views/books/_form.html.erb
<%= form_for([current_user, @book], html: { multipart: true }) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, size: '43x5' %>
  </div>

  <div class="field">
    <%= f.label 'Bookfile (allowed only pdf)' %><br />
    <%- unless @book.new_record? %>
      <%= f.label 'Current bookfile: '%><%= render partial: 'download_book', object: @book %><br />
    <%- end %>
    <%= f.file_field :bookfile %>
  </div>

  <div class="actions">
    <%= f.submit %> or <%= link_to 'Cancel', user_books_path(current_user) %>
  </div>
<% end %>

app/views/books/_recently_added.html.erb
<h2>Recently added books</h2>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Author</th>
    <th>Added at</th>
  </tr>

<% @recently_added_books.each do |book| %>
  <tr>
    <td><%= link_to book.title, book, title: 'Show book' %></td>
    <td><%= book.description %></td>
    <td><%= book.user.name %></td>
    <td><%= book.created_at.to_s(:db) %></td>
  </tr>
<% end %>
</table>

app/views/books/edit.html.erb
<h1>Edit book</h1>
<%= render 'form' %>

app/views/books/index.html.erb
<h2>
  <%- if @author %>
      <%- if @author == current_user %>
          My Books
      <%- else %>
          Listing books <%= "for author #{@author.name}" %>
      <%- end %>
  <%- else %>
    Books
  <%- end %>
</h2>
  <%- if @books.any? %>
    <table>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <%- if @author %>
            <th></th>
        <%- else %>
            <th>Author</th>
        <%- end %>
        <th>Bookfile</th>
        <th></th>
        <th></th>
      </tr>

      <%- @books.each do |book| %>
        <tr>
          <%- if @author %>
              <td><%= link_to book.title, user_book_path(book.user, book), title: 'Show book' %></td>
          <%- else %>
              <td><%= link_to book.title, book, title: 'Show book' %></td>
          <%- end %>

          <td><%= book.description %></td>
          <%- if @author %>
              <td></td>
          <%- else %>
              <td><%= book.user.name %></td>
          <%- end %>

          <td><%= render partial: 'download_book', object: book %></td>

          <%- if user_signed_in? && current_user == @author %>
              <td><%= link_to 'Edit', edit_user_book_path(current_user, book) %></td>
              <td><%= link_to 'Destroy', user_book_path(current_user, book), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%- else %>
              <td></td>
              <td></td>
          <%- end %>
        </tr>
      <%- end %>

      </table>
  <%- else %>
    <p>No uploaded books currently</p>
  <%- end %>

<br />

<%- if user_signed_in? && current_user == @author %>
  <%= link_to 'Add New Book', new_user_book_path(current_user) %>
<%- end %>

app/views/books/new.html.erb
<h1>Add new book</h1>
<%= render 'form' %>

app/views/books/show.html.erb
<h2>Book info</h2>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Description:</b>
  <%= @book.description %>
</p>

<p>
  <b>Author:</b>
  <%= @book.user.email %>
</p>

<p>
  <b>Bookfile:</b>
  <%= render partial: 'download_book', object: @book %>
</p>

<%- if @author %>
    <%- if @author == current_user %>
        <%= link_to 'My Books', user_books_path(@author) %>
    <%- else %>
        <%= link_to 'Books', user_books_path(@author) %>
    <%- end %>
<%- else %>
  <%= link_to 'Books', books_path %>
<%- end %>

<%- if @book.user == current_user %>
    | <%= link_to 'Edit', edit_user_book_path(current_user, @book) %>
<%- end %>

app/views/home/index.html.erb
<%- if user_signed_in? %>
  <p>
    Currently you have <%= current_user.books_count %> uploaded books.
    Do you want to <%= link_to 'add books', new_user_book_path(current_user) %>?
  </p>
<%- else %>
  <p>
    Are you the author?
    <%= link_to "Sign up", new_registration_path(:user) %> or <%= link_to "sign in", new_user_session_path %> and upload your books !
  </p>
<%- end %>

<%= render 'users/by_count_of_books' if @user_by_count_of_books.any? %>
<%= render 'books/recently_added' if @recently_added_books.any? %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleLib</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>Simple library</h1>

  <div id="menu">
    <%= link_to 'Home', root_path %>
    <%= link_to 'Authors', users_path %>
    <%= link_to 'Books', books_path %>
    |
    <%- if user_signed_in? %>
      <%= link_to 'My Books', user_books_path(current_user) %>

      <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
        (logged as: <%= current_user.name %>, <%= current_user.email %>)
    <%- else %>
      <%= link_to "Sign in", new_user_session_path %>
    <%- end  %>
  </div>
  <div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>

  <%= yield %>

</body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleLib</title>
  <style type="text/css">
    body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }
    div.dialog {
      width: 25em;
      padding: 0 4em;
      margin: 4em auto 0 auto;
      border: 1px solid #ccc;
      border-right-color: #999;
      border-bottom-color: #999;
    }
    h1 { font-size: 100%; color: #f00; line-height: 1.5em; }
  </style>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/users/_by_count_of_books.html.erb
<h2>Top <%= User::TOP_BY_COUNT_OF_BOOKS %> authors by count of books</h2>

<table>
  <tr>
    <th>Author</th>
    <th>Books</th>
  </tr>

<% @user_by_count_of_books.each do |user| %>
  <tr>
    <td><%= link_to user.name, user_books_path(user), title: 'Show books' %></td>
    <td><%= user.books_count %></td>
  </tr>
<% end %>
</table>

app/views/users/index.html.erb
<h2>Authors</h2>

<%- if @users.any? %>
    <table>
      <tr>
        <th>Author</th>
        <th>Books count</th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user_books_path(user), title: 'Show author\'s books' %></td>
          <td><%= user.books.size %></td>
        </tr>
      <% end %>
    </table>
<%- else %>
  <p>No registered authors currently</p>
<%- end %>